# Generated by Django 4.2 on 2023-08-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('comment', models.TextField(max_length=5000)),
                ('publish_date', models.TimeField()),
            ],
        ),
    ]
